### ISSUE TITLE
[Enhancement]: Onboard test-frame repository to sonarcloud analysis

### ISSUE THREAD

**Issue by kornys** [skodjob/test-frame#254]
### Related problem

We would like to have sonarcloud code analysis solution implemented for our codebase.

### Suggested solution

1. Create gh account or reuse existing github service account
2. Create sonarcloud account using github account
3. Create public oorganization in sonarcloud
4. Add test-frame repository into sonarcloud organization
5. Configure repo to use GH action
6. Add secrets into github organization
7. Use similar action
```
name: SonarCloud Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 11 (or desired version)
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B clean verify

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=YOUR_PROJECT_KEY
            -Dsonar.organization=YOUR_SONARCLOUD_ORG
            -Dsonar.host.url=https://sonarcloud.io
            # If you have coverage reports or additional config, pass them as well
            # -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

```
